AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackFamily:
    Type: String
    Default: ecs-blue-green-board
  StackFamilyEnvironment:
    Type: String
    Default: test
  EcsDesiredCount:
    Type: Number
    Default: 1
  EcsCpu:
    Type: Number
    Default: 512
  TaskMemory:
    Type: Number
    Default: 2048
  ApiMemory:
    Type: Number
    Default: 1536
  ClientMemory:
    Type: Number
    Default: 1536

Transform:
  - 'AWS::CodeDeployBlueGreen'

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${StackFamily}-app"
      RetentionInDays: 14

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      RoleName: !Sub "${StackFamily}-test-ecs-execution"

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: 'ExecuteCommandPermissions'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: [
                  "ssmmessages:CreateControlChannel",
                  "ssmmessages:OpenControlChannel",
                  "ssmmessages:CreateDataChannel",
                  "ssmmessages:OpenDataChannel"
                ]
                Resource: "*"
              - Effect: 'Allow'
                Action: [
                  "logs:CreateLogStream",
                  "logs:DescribeLogGroups",
                  "logs:DescribeLogStreams",
                  "logs:PutLogEvents"
                ]
                Resource: "*"
      Path: "/"
      RoleName: !Sub "${StackFamily}-test-ecs-task"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${StackFamily}-app"
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      NetworkMode: awsvpc
      Volumes:
        - Host: {}
          Name: uds
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref EcsCpu
      ContainerDefinitions:
        - Name: sharetheboard-api
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StackFamily}/sharetheboard-api:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "${StackFamily}-app"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
              Protocol: tcp
          Secrets:
            - Name: NODE_ENV
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/NODE_ENV
            - Name: APP_PORT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_PORT
            - Name: APP_HOST
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_HOST
            - Name: APP_LOGGER_LEVEL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_LOGGER_LEVEL
            - Name: APP_URL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_URL
            - Name: APP_DATABASE_SECRET_URL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_DATABASE_SECRET_URL
            - Name: APP_DATABASE_LOGGER_LEVEL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_DATABASE_LOGGER_LEVEL
            - Name: APP_SESSION_DOMAIN
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_DOMAIN
            - Name: APP_SESSION_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_SECRET
            - Name: APP_DATABASE_MIGRATIONS_AUTORUN
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_DATABASE_MIGRATIONS_AUTORUN
            - Name: APP_SESSION_TIMEOUT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_TIMEOUT
            - Name: APP_SESSION_REFRESH_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_REFRESH_SECRET
            - Name: APP_SESSION_REFRESH_TIMEOUT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_REFRESH_TIMEOUT
            - Name: APP_WHITELIST_DOMAINS
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WHITELIST_DOMAINS
            - Name: APP_FACEBOOK_APP_ID
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_FACEBOOK_APP_ID
            - Name: APP_FACEBOOK_APP_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_FACEBOOK_APP_SECRET
            - Name: APP_GOOGLE_CLIENT_ID
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_GOOGLE_CLIENT_ID
            - Name: APP_GOOGLE_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_GOOGLE_SECRET
            - Name: APP_SMTP_MAIL_SENDER
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SMTP_MAIL_SENDER
            - Name: APP_SMTP_API_HOST
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SMTP_API_HOST
            - Name: APP_SMTP_API_PORT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SMTP_API_PORT
            - Name: APP_SMTP_API_CLIENT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SMTP_API_CLIENT
            - Name: APP_SMTP_API_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SMTP_API_SECRET
            - Name: APP_RABBITMQ_URI
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_RABBITMQ_URI
            - Name: APP_CLIENT_PLAN_ACCESS_KEY_ID
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_CLIENT_PLAN_ACCESS_KEY_ID
            - Name: APP_CLIENT_PLAN_SECRET_ACCESS_KEY_ID
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_CLIENT_PLAN_SECRET_ACCESS_KEY_ID
            - Name: APP_SESSION_PASSWORD_RESET_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_PASSWORD_RESET_SECRET
            - Name: APP_SESSION_PASSWORD_RESTET_TIMEOUT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_PASSWORD_RESTET_TIMEOUT
            - Name: APP_SESSION_VERIFICATION_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_VERIFICATION_SECRET
            - Name: APP_SESSION_VERIFICATION_TIMEOUT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_SESSION_VERIFICATION_TIMEOUT
            - Name: APP_FEATURE_FLAG_JWT_WS_GUARD
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_FEATURE_FLAG_JWT_WS_GUARD
            - Name: APP_REDIS_URL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_REDIS_URL
            - Name: APP_HASHIDS_SALT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_HASHIDS_SALT
            - Name: APP_HASHIDS_MIN_LENGTH
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_HASHIDS_MIN_LENGTH
            - Name: APP_WS_SESSION_SECRET
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_SECRET
            - Name: APP_WS_SESSION_SAVE_UNINITIALIZED
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_SAVE_UNINITIALIZED
            - Name: APP_WS_SESSION_RESAVE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_RESAVE
            - Name: APP_WS_SESSION_COOKIE_SECURE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_COOKIE_SECURE
            - Name: APP_WS_SESSION_COOKIE_HTTP_ONLY
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_COOKIE_HTTP_ONLY
            - Name: APP_WS_SESSION_COOKIE_SAME_SITE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_COOKIE_SAME_SITE
            - Name: APP_WS_SESSION_COOKIE_MAX_AGE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_COOKIE_MAX_AGE
            - Name: APP_WS_SESSION_COOKIE_DOMAIN
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/APP_WS_SESSION_COOKIE_DOMAIN
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8000/api/healthcheck
            Interval: 30
            Retries: 3
            Timeout: 30
          Ulimits:
            - Name: nofile
              SoftLimit: 65536
              HardLimit: 65536
          MountPoints:
            - SourceVolume: uds
              ContainerPath: /var/run
          Memory: !Ref ApiMemory
        - Name: sharetheboard-client
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StackFamily}/sharetheboard-client:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "${StackFamily}-app"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
            - ContainerPort: 443
              HostPort: 443
              Protocol: tcp
          Secrets:
            - Name: VITE_SOCKET_URL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/VITE_SOCKET_URL
            - Name: VITE_ENABLE_XSTATE_INSPECTOR
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/VITE_ENABLE_XSTATE_INSPECTOR
            - Name: VITE_DASHBOARD_URL
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/VITE_DASHBOARD_URL
            - Name: VITE_STB_ENVIRONMENT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/env/staging/VITE_STB_ENVIRONMENT
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost/healthcheck
          DependsOn:
            - ContainerName: sharetheboard-api
              Condition: HEALTHY
          Ulimits:
            - Name: nofile
              SoftLimit: 65536
              HardLimit: 65536
          MountPoints:
            - SourceVolume: uds
              ContainerPath: /var/run
          Memory: !Ref ClientMemory

  # DiscoveryService:
  #   Type: AWS::ServiceDiscovery::Service
  #   Properties:
  #     DnsConfig:
  #       RoutingPolicy: MULTIVALUE
  #       DnsRecords:
  #         - TTL: 60
  #           Type: A
  #         - TTL: 60
  #           Type: SRV
  #     HealthCheckCustomConfig:
  #       FailureThreshold: 1
  #     Name: !Sub "${StackFamily}-${StackFamilyEnvironment}"
  #     NamespaceId:
  #       Fn::ImportValue:
  #         !Sub "${StackFamily}-PrivateNamespace"
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub "${StackFamily}-ecs-cluster"
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      # ServiceRegistries:
      #   - RegistryArn: !GetAtt DiscoveryService.Arn
      #     Port: 80
      DesiredCount: !Ref EcsDesiredCount
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue:
                !Sub "${StackFamily}-private-subnet-1a"
            - Fn::ImportValue:
                !Sub "${StackFamily}-private-subnet-1b"
          SecurityGroups:
            - Fn::ImportValue:
                !Sub "${StackFamily}-app-sg"
      LoadBalancers:
        - ContainerName: sharetheboard-client
          ContainerPort: 80
          TargetGroupArn:
            Fn::ImportValue:
              !Sub "${StackFamily}-target-group-blue"
        - ContainerName: sharetheboard-api
          ContainerPort: 8000
          TargetGroupArn:
            Fn::ImportValue:
              !Sub "${StackFamily}-target-group-blue-api"
      HealthCheckGracePeriodSeconds: 30
      ServiceName: !Sub "${StackFamily}-app"
      DeploymentController:
        Type: CODE_DEPLOY
      SchedulingStrategy: "REPLICA"
