AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackFamily:
    Type: String
    Default: ecs-blue-green-board
  AccessToken:
    Type: String
    NoEcho: true

Resources:
  SecretsManagerSecretGitHub:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${StackFamily}-secrets-github"
      Description: github personal access token
      SecretString: !Sub |
        {
          "access-token": "${AccessToken}"
        }
