AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackFamily:
    Type: String
    Default: ecs-blue-green-board
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
  SubnetCidrBlockPrivate1a:
    Type: String
    Default: 10.0.1.0/24
  SubnetCidrBlockPrivate1b:
    Type: String
    Default: 10.0.2.0/24
  SubnetCidrBlockPublic1a:
    Type: String
    Default: 10.0.3.0/24
  SubnetCidrBlockPublic1b:
    Type: String
    Default: 10.0.4.0/24

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${StackFamily}-vpc"

  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: 'eu-central-1a'
      CidrBlock: !Ref SubnetCidrBlockPrivate1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${StackFamily}-private-subnet-1a"

  PrivateSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: 'eu-central-1b'
      CidrBlock: !Ref SubnetCidrBlockPrivate1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${StackFamily}-private-subnet-1b"

  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: 'eu-central-1a'
      CidrBlock: !Ref SubnetCidrBlockPublic1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${StackFamily}-public-subnet-1a"

  PublicSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: 'eu-central-1b'
      CidrBlock: !Ref SubnetCidrBlockPublic1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${StackFamily}-public-subnet-1b"

Outputs:
  VPC:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${StackFamily}-vpc"
  PrivateSubnet1a:
    Value: !Ref PrivateSubnet1a
    Export:
      Name: !Sub "${StackFamily}-private-subnet-1a"
  PrivateSubnet1b:
    Value: !Ref PrivateSubnet1b
    Export:
      Name: !Sub "${StackFamily}-private-subnet-1b"
  PublicSubnet1a:
    Value: !Ref PublicSubnet1a
    Export:
      Name: !Sub "${StackFamily}-public-subnet-1a"
  PublicSubnet1b:
    Value: !Ref PublicSubnet1b
    Export:
      Name: !Sub "${StackFamily}-public-subnet-1b"
  SubnetCidrBlockPrivate1a:
    Value: !Ref SubnetCidrBlockPrivate1a
    Export:
      Name: !Sub "${StackFamily}-cidr-private-1a"
  SubnetCidrBlockPrivate1b:
    Value: !Ref SubnetCidrBlockPrivate1b
    Export:
      Name: !Sub "${StackFamily}-cidr-private-1b"
  SubnetCidrBlockPublic1a:
    Value: !Ref SubnetCidrBlockPublic1a
    Export:
      Name: !Sub "${StackFamily}-cidr-public-1a"
  SubnetCidrBlockPublic1b:
    Value: !Ref SubnetCidrBlockPublic1b
    Export:
      Name: !Sub "${StackFamily}-cidr-public-1b"
